$clean_ext = 'bbl nav snm run.xml vrb synctex pdf Identifier out xdv';
$pdf_mode = 5;
$postscript_mode = $dvi_mode = 0;
$xelatex = 'xelatex -no-pdf -shell-escape -synctex=15 %O %S';
$pdf_previewer = 'okular';

@default_files = ('talia-concurrency-2.tex');
